mynnbasedclassifier/diy/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('index/', views.index),
    path('classifyResult/', views.classifyResult, name = 'name_classifyResult'),
]

mynnbasedclassifier/mynnbasedclassifier/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nnbasedclassifier/', include(('nnbasedclassifier.urls', 'a'), namespace = 'namespace_classifier')),
]

mynnbasedclassifier/nnbasedclassifier/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('index/', views.index, name = 'name_index'),
    path('typeChoose/', views.typeChoose, name = 'name_datasetChoose'),
    path('mnist/', include(('mnist.urls', 'a'), namespace = 'namespace_mnist')),
    path('cifar10/', include(('cifar10.urls', 'a'), namespace = 'namespace_cifar10')),
    path('diy/', include(('diy.urls', 'a'), namespace = 'namespace_diy')),
]

mynnbasedclassifier/nnbasedclassifier/models.py
from django.db import models

# Create your models here.

mynnbasedclassifier/nnbasedclassifier/views.py
from django.shortcuts import render

from . import models

from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, 'entrance/index.html')

def typeChoose(request):
    da_type = request.POST.get('da_type', 'MNIST')
    if da_type == 'MNIST':
        return render(request, 'mnist/index.html')
    elif da_type == 'CIFAR10':
        return render(request, 'cifar10/index.html')
    else:
        return render(request, 'diy/index.html')
        #return HttpResponse('Welcome, this method is '+da_type+'')

mynnbasedclassifier/nnbasedclassifier/templates/entrance/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>homepage</title>
</head>
<body bgcolor = "#161F25">
<font color="E8EBEC" size = "10"><B><div style = "padding-left:5%; padding-top:5%;">Welcome, this is root homepage!</div></B></font>
<br/>
<h3><font color="#B5C0C2" size = "6"><div style = "padding-left:7.5%">Please choose a dataset.</div></font></h3>
<form action = '{% url 'namespace_classifier:name_datasetChoose' %}' method = 'post'>
    {% csrf_token %}
    <div style = "padding-left:9%">
    <font color="#B5C0C2" size = "4.5">
    <input type = 'radio' name = 'da_type' value = 'MNIST' checked=""/> MNIST<br/>
    <input type = 'radio' name = 'da_type' value = 'CIFAR10' /> CIFAR10<br/>
    <input type = 'radio' name = 'da_type' value = 'DIY' /> DIY<br/><br/>
    <input type = 'submit' value = 'Submit' style = "font-size:20px"/>
    </font>
    </div>
</form>
{% load static %}
<img src="{% static "index_cover.jpg" %}" alt="Sample Display">
<br>
<footer><font color="B5C0C2" size = "3">Copyrights @ Zihan Rubio</font></footer>
</body>
</html>