mynnbasedclassifier/diy/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('index/', views.index),
    path('classifyResult/', views.classifyResult, name = 'name_classifyResult'),
]

mynnbasedclassifier/mnist/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('index/', views.index),
    path('typeChoose/', views.typeChoose, name = 'name_typeChoose'),
    path('hitRate/', views.hitRate, name = 'name_hitRate'),
]

mynnbasedclassifier/mynnbasedclassifier/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nnbasedclassifier/', include(('nnbasedclassifier.urls', 'a'), namespace = 'namespace_classifier')),
]

mynnbasedclassifier/nnbasedclassifier/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('index/', views.index, name = 'name_index'),
    path('typeChoose/', views.typeChoose, name = 'name_datasetChoose'),
    path('mnist/', include(('mnist.urls', 'a'), namespace = 'namespace_mnist')),
    path('cifar10/', include(('cifar10.urls', 'a'), namespace = 'namespace_cifar10')),
    path('diy/', include(('diy.urls', 'a'), namespace = 'namespace_diy')),
]

mynnbasedclassifier/mnist/models.py
from django.db import models

# Create your models here.

class training_record_mnist(models.Model):
    record_mnist = models.CharField(max_length = 2048, default = "No record")

mynnbasedclassifier/nnbasedclassifier/models.py
from django.db import models

# Create your models here.

mynnbasedclassifier/mnist/views.py
from django.shortcuts import render

from . import models

from django.http import HttpResponse

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

from numpy import outer
from pyexpat import features

# Create your views here.

def index(request):
    return render(request, 'mnist/index.html')

def typeChoose(request):
    nn_type = request.POST.get('nn_type', 'BP')
    return render(request, 'mnist/para.html', {'nn_type': nn_type})
    #return HttpResponse('Welcome, this method is '+nn_type+'.')

def hitRate(request):
    nn_type = request.POST.get('nn_type', 'BP')
    mnist = input_data.read_data_sets("MNIST_data", one_hot=True)

    # parameters
    if nn_type == 'BP':
        learning_rate = float(request.POST.get('learning_rate', 0.5))
    else:
        learning_rate = float(request.POST.get('learning_rate', 0.001))

    training_epochs = int(request.POST.get('training_epochs', 5))
    batch_size = int(request.POST.get('batch_size', 100))
    display_step = int(request.POST.get('display_step', 1))

    # initial output string
    s = []
    temp = "-------------------Parameters setting-------------------"
    s.append(temp)
    temp = "Method : " + nn_type
    s.append(temp)
    temp = "Learning_rate = " + "{:.4f}".format(learning_rate)
    s.append(temp)
    temp = "Training_epochs = " + '%04d' % training_epochs
    s.append(temp)
    temp = "Batch_size = " + '%04d' % batch_size
    s.append(temp)
    temp = "Display_step = " + '%04d' % display_step
    s.append(temp)
    temp = "-------------------Training progress-------------------"
    s.append(temp)

    if nn_type == 'BP':

        # initialization
        x = tf.placeholder(tf.float32, [None, 784])  # ? * 784 (28^2)
        y_ = tf.placeholder(tf.float32, [None, 10])  # ? * 10 types
        W = tf.Variable(tf.zeros([784, 10]))  # weight
        b = tf.Variable(tf.zeros([10]))  # bias counter
        y = tf.nn.softmax(tf.matmul(x, W) + b)  # prediction x matrix(*) W matrix(+) b

        # model
        cross_entropy = tf.reduce_mean(
            tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=tf.log(y)))  # cross entropy
        train_step = tf.train.GradientDescentOptimizer(learning_rate).minimize(cross_entropy)  # minimize loss function
        init = tf.global_variables_initializer()  # initialize model
        sess = tf.InteractiveSession()  # build interactive session
        sess.run(init)  # run

        # train
        for epoch in range(training_epochs):
            total_batch = int(mnist.train._num_examples / batch_size)
            for i in range(total_batch):
                batch_x, batch_y = mnist.train.next_batch(batch_size)
                sess.run(train_step, feed_dict={x: batch_x, y_: batch_y})
            if epoch % display_step == 0:
                correct_prediction = tf.equal(tf.arg_max(y, 1), tf.arg_max(y_, 1))  # compare
                accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))  # transform type
                temp = "Epoch : " + '%04d' % (epoch + 1) + ", Accuracy = " + "{:.4f}".format(
                    sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels})) + "\n"
                s.append(temp)
            # print(s)
            # print("Epoch:", '%04d' % (epoch+1), "Accuracy =", "{:.4f}".format(sess.run(accuracy,feed_dict = {x:mnist.test.images,y_:mnist.test.labels})))

        temp = "-------------------Final result-------------------"
        s.append(temp)
        correct_prediction = tf.equal(tf.arg_max(y, 1), tf.arg_max(y_, 1))  # compare
        accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))  # transform type
        temp = "Epoch : " + '%04d' % (epoch + 1) + ", Accuracy = " + "{:.4f}".format(
            sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels}))  # test and output
        s.append(temp)

        #return HttpResponse(nn_type+' '+movement)

    elif nn_type == 'CNN':

        # network Parameters
        n_input = 784  # MNIST data input(image shape = [28,28])
        n_classes = 10  # MNIST total classes (0-9digits)
        dropout = 0.75  # probability to keep units

        # tf Graph input
        x = tf.placeholder(tf.float32, [None, n_input])
        y = tf.placeholder(tf.float32, [None, n_classes])
        keep_prob = tf.placeholder(tf.float32)  # drop(keep probability)

        # step definition
        def conv2d(image, w, b):
            return tf.nn.relu(tf.nn.bias_add(tf.nn.conv2d(image, w, strides=[1, 1, 1, 1], padding='SAME'), b))

        def max_pooling(image, k):
            return tf.nn.max_pool(image, ksize=[1, k, k, 1], strides=[1, k, k, 1], padding='SAME')

        weights = {
            'wc1': tf.Variable(tf.random_normal([5, 5, 1, 32])),
            'wc2': tf.Variable(tf.random_normal([5, 5, 32, 64])),
            'wd1': tf.Variable(tf.random_normal([7 * 7 * 64, 1024])),
            'out': tf.Variable(tf.random_normal([1024, n_classes]))
        }

        biases = {
            'bc1': tf.Variable(tf.random_normal([32])),
            'bc2': tf.Variable(tf.random_normal([64])),
            'bd1': tf.Variable(tf.random_normal([1024])),
            'out': tf.Variable(tf.random_normal([n_classes]))
        }

        def conv_net(_X, _weights, _biases, _dropout):
            # Layer 1
            _X = tf.reshape(_X, [-1, 28, 28, 1])
            conv1 = conv2d(_X, _weights['wc1'], _biases['bc1'])
            conv1 = max_pooling(conv1, k=2)
            conv1 = tf.nn.dropout(conv1, keep_prob=_dropout)
            # Layer 2
            conv2 = conv2d(conv1, _weights['wc2'], _biases['bc2'])
            conv2 = max_pooling(conv2, k=2)
            conv2 = tf.nn.dropout(conv2, keep_prob=_dropout)
            # Fully Connected
            dense1 = tf.reshape(conv2, [-1, _weights['wd1'].get_shape().as_list()[0]])
            dense1 = tf.nn.relu(tf.add(tf.matmul(dense1, _weights['wd1']), _biases['bd1']))
            dense1 = tf.nn.dropout(dense1, _dropout)
            out = tf.add(tf.matmul(dense1, _weights['out']), _biases['out'])
            print(out)
            return out

        # model
        pred = conv_net(x, weights, biases, keep_prob)
        cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y, logits=pred))
        optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)
        correct_pred = tf.equal(tf.argmax(pred, 1), tf.argmax(y, 1))
        accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))
        init = tf.initialize_all_variables()
        saver = tf.train.Saver()

        with tf.Session() as sess:
            sess.run(init)
            saver.restore(sess, "model_tmp/mnist_demo.ckpt")
            # Training cycle
            for epoch in range(training_epochs):
                total_batch = int(mnist.train._num_examples / batch_size)
                for i in range(total_batch):
                    batch_xs, batch_ys = mnist.train.next_batch(batch_size)
                    sess.run(optimizer, feed_dict={x: batch_xs, y: batch_ys, keep_prob: dropout})
                if epoch % display_step == 0:
                    acc = sess.run(accuracy, feed_dict={x: mnist.test.images, y: mnist.test.labels, keep_prob: 1.})
                    loss = sess.run(cost, feed_dict={x: batch_xs, y: batch_ys, keep_prob: 1.})
                    temp = "Epoch : " + '%04d' % (epoch + 1) + ", Minibatch Loss = " + "{:.4f}".format(
                        loss) + ", Accuracy = " + "{:.4f}".format(acc)
                    s.append(temp)
            saver.save(sess, "model_tmp/mnist_demo.ckpt")

            temp = "-------------------Final result-------------------"
            s.append(temp)
            temp = "Epoch : " + '%04d' % (epoch + 1) + ", Minibatch Loss = " + "{:.4f}".format(
                loss) + ", Accuracy = " + "{:.4f}".format(acc)
            s.append(temp)

    elif nn_type == 'CNN_SIGMOID':

        # network Parameters
        n_input = 784  # MNIST data input(image shape = [28,28])
        n_classes = 10  # MNIST total classes (0-9digits)
        dropout = 0.75  # probability to keep units

        # tf Graph input
        x = tf.placeholder(tf.float32, [None, n_input])
        y = tf.placeholder(tf.float32, [None, n_classes])
        keep_prob = tf.placeholder(tf.float32)  # drop(keep probability)

        # step definition
        def conv2d(image, w, b):
            return tf.nn.sigmoid(tf.nn.bias_add(tf.nn.conv2d(image, w, strides=[1, 1, 1, 1], padding='SAME'), b))

        def max_pooling(image, k):
            return tf.nn.max_pool(image, ksize=[1, k, k, 1], strides=[1, k, k, 1], padding='SAME')

        weights = {
            'wc1': tf.Variable(tf.random_normal([5, 5, 1, 32])),
            'wc2': tf.Variable(tf.random_normal([5, 5, 32, 64])),
            'wd1': tf.Variable(tf.random_normal([7 * 7 * 64, 1024])),
            'out': tf.Variable(tf.random_normal([1024, n_classes]))
        }

        biases = {
            'bc1': tf.Variable(tf.random_normal([32])),
            'bc2': tf.Variable(tf.random_normal([64])),
            'bd1': tf.Variable(tf.random_normal([1024])),
            'out': tf.Variable(tf.random_normal([n_classes]))
        }

        def conv_net(_X, _weights, _biases, _dropout):
            # Layer 1
            _X = tf.reshape(_X, [-1, 28, 28, 1])
            conv1 = conv2d(_X, _weights['wc1'], _biases['bc1'])
            conv1 = max_pooling(conv1, k=2)
            conv1 = tf.nn.dropout(conv1, keep_prob=_dropout)
            # Layer 2
            conv2 = conv2d(conv1, _weights['wc2'], _biases['bc2'])
            conv2 = max_pooling(conv2, k=2)
            conv2 = tf.nn.dropout(conv2, keep_prob=_dropout)
            # Fully Connected
            dense1 = tf.reshape(conv2, [-1, _weights['wd1'].get_shape().as_list()[0]])
            dense1 = tf.nn.sigmoid(tf.add(tf.matmul(dense1, _weights['wd1']), _biases['bd1']))
            dense1 = tf.nn.dropout(dense1, _dropout)

mynnbasedclassifier/nnbasedclassifier/views.py
from django.shortcuts import render

from . import models

from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, 'entrance/index.html')

def typeChoose(request):
    da_type = request.POST.get('da_type', 'MNIST')
    if da_type == 'MNIST':
        return render(request, 'mnist/index.html')
    elif da_type == 'CIFAR10':
        return render(request, 'cifar10/index.html')
    else:
        return render(request, 'diy/index.html')
        #return HttpResponse('Welcome, this method is '+da_type+'')

mynnbasedclassifier/nnbasedclassifier/templates/mnist/accuracy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>accuracy display</title>
</head>
<body bgcolor = "#161F25">
<font color="E8EBEC" size = "10"><B><div style = "padding-left:5%; padding-top:5%;">Welcome, this is accuracy display page for dataset mnist.</div></B></font>
<font color="B5C0C2" size = "5"><B><div style = "padding-left:7.5%; padding-top:5%;">
    {% for item in s %}
    {{ item }}<br>
    {% endfor %}
</div></B></font>
<br><br>

<!-- Container -->
<div id="main" style="height:400px"></div>
<!-- ECharts单文件引入 -->
<script src="http://echarts.baidu.com/build/dist/echarts.js"></script>
<script type="text/javascript">
    require.config({
        paths: {
            echarts: 'http://echarts.baidu.com/build/dist'
        }
    });

    // 使用
    require(
        [
            'echarts',
            'echarts/chart/bar'
        ],
        function (ec) {
            var myChart = ec.init(document.getElementById('main'));

            var option = {
                title: {
                    text: 'Accuracy Result Display ( Epoch = 5 )',
                    textStyle:{
                        color: '#B5C0C2',
                        fontWeight: 'bold',
                        fontSize: 32
                    }
                },
                tooltip: {
                    show: true
                },
                legend: {
                    data:['Accuracy Rate'],
                    textStyle:{
                        color: '#B5C0C2',
                        fontSize: 24
                    }
                },
                xAxis : [
                    {
                        type : 'category',
                        data : ["BP","CNN","CNN_SIGMOID","CNN_DROPOUT","CNN_ARCH","DNN","ANN"],
                        axisLabel : {
                            formatter: '{value}',
                            textStyle: {
                                color: '#B5C0C2',
                                fontSize: 18
                            }
                        }
                    }
                ],
                yAxis : [
                    {
                        scale : true,
                        min : 'dataMin',
                        max : 'dataMax',
                        type : 'value',
                        axisLabel : {
                            formatter: '{value}',
                            textStyle: {
                                color: '#B5C0C2',
                                fontSize: 24
                            }
                        }
                    }
                ],
                series : [
                    {
                        "name":"Accuracy Rate",
                        "type":"bar",
                        itemStyle:{
                            normal:{
                                barStyle:{
                                    color:'#B5C0C2'
                                }
                            }
                        },
                        "data":[0.9212, 0.9622, 0.7605, 0.9739, 0.9919, 0.9726, 0.9063]
                    }
                ]
            };

            myChart.setOption(option);
        }
    );
</script>

<div style = "padding-left:5%; padding-top:5%;"><a href="{% url 'namespace_classifier:name_index' %}" style = "color:#CBEB3C; size = "6"">Back to homepage >>></a></div>
<br>
<footer><font color="B5C0C2" size = "3">Copyrights @ Zihan Rubio</font></footer>
</body>
</html>

mynnbasedclassifier/nnbasedclassifier/templates/mnist/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>mnist homepage</title>
</head>
<body bgcolor = "#161F25">
<font color="E8EBEC" size = "10"><B><div style = "padding-left:5%; padding-top:5%;">Welcome, this is mnist homepage!</div></B></font>
<br/>
<h3><font color="#B5C0C2" size = "6"><div style = "padding-left:7.5%">Please choose a NN type.</div></font></h3>
<form action = '{% url 'namespace_classifier:namespace_mnist:name_typeChoose' %}' method = 'post'>
    {% csrf_token %}
    <div style = "padding-left:9%">
    <font color="#B5C0C2" size = "4.5">
    <input type = 'radio' name = 'nn_type' value = 'BP' checked=""/> BP<br/>
    <input type = 'radio' name = 'nn_type' value = 'CNN' /> CNN<br/>
    <input type = 'radio' name = 'nn_type' value = 'CNN_SIGMOID' /> CNN_sigmoid_function<br/>
    <input type = 'radio' name = 'nn_type' value = 'CNN_DROPOUT' /> CNN_no_dropout_layer<br/>
    <input type = 'radio' name = 'nn_type' value = 'CNN_ARCH' /> CNN_architecture_advanced<br/>
    <input type = 'radio' name = 'nn_type' value = 'DNN' /> DNN<br/>
    <input type = 'radio' name = 'nn_type' value = 'ANN' /> ANN<br/><br/>
    <input type = 'submit' value = 'Submit' style = "font-size:20px"/>
    </font>
    </div>
</form>
<br>
<footer style="position:absolute; bottom:0;"><font color="B5C0C2" size = "3">Copyrights @ Zihan Rubio</font></footer>
</body>
</html>

mynnbasedclassifier/nnbasedclassifier/templates/mnist/para.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>parameter for mnist</title>
</head>
<body bgcolor = "#161F25">
<font color="E8EBEC" size = "10"><B><div style = "padding-left:5%; padding-top:5%;">Welcome, this is parameter setting page for dataset mnist.</div></B></font>
<br/>
<h3><font color="#B5C0C2" size = "6"><div style = "padding-left:7.5%">Please input following parameters for {{ nn_type }}.</div></font></h3>
<form action = '{% url 'namespace_classifier:namespace_mnist:name_hitRate' %}' method = 'post'>
    {% csrf_token %}
    <div style = "padding-left:9%">
    <font color="#B5C0C2" size = "4.5">
    <input type = 'hidden' name = 'nn_type' value = '{{ nn_type | default:'BP' }}'/>
    {% if nn_type == 'BP' %}
        <label>learning_rate
            <input type = 'text' name = 'learning_rate' value = 0.5 />
        </label>
        <br/>
    {% endif %}
    {% if nn_type != 'BP' %}
        <label>learning_rate
            <input type = 'text' name = 'learning_rate' value = 0.001 />
        </label>
        <br/>
    {% endif %}

    <label>training_epochs
        <input type = 'text' name = 'training_epochs' value = 5 />
    </label>
    <br/>

    <label>batch_size
        <input type = 'text' name = 'batch_size' value = 100 />
    </label>
    <br/>

    <label>display_step
        <input type = 'text' name = 'display_step' value = 1 />
    </label>
    <br/>

    <br/><input type = 'submit' value = 'Submit' style = "font-size:20px"/>
    </font>
    </div>
</form>
<br>
<footer style="position:absolute; bottom:0;"><font color="B5C0C2" size = "3">Copyrights @ Zihan Rubio</font></footer>
</body>
</html>